import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { CtaButton } from "../components/CtaButton";
import { SlideButton } from "../components/SlideButton";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tesla</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section id="model-3">
          <div className="relative z-0 h-screen w-screen">
            <div className="absolute inset-0 -z-10 h-screen w-screen overflow-hidden">
              <Image
                src={
                  "https://tesla-cdn.thron.com/delivery/public/image/tesla/9160c5a3-b818-42dd-bb98-b8597948c636/bvlatuR/std/1927x4096/M3-Homepage-Mobile-LHD"
                }
                alt="model-3"
                width={500}
                height={800}
                className="h-screen w-full object-cover object-center sm:hidden"
                priority={true}
              />
              <Image
                src={
                  "https://tesla-cdn.thron.com/delivery/public/image/tesla/03e533bf-8b1d-463f-9813-9a597aafb280/bvlatuR/std/4096x2560/M3-Homepage-Desktop-LHD"
                }
                alt="model-3"
                width={2000}
                height={2000}
                className="hidden h-screen w-screen object-cover object-center sm:block"
                priority={true}
              />
            </div>
            <div className="flex h-screen items-center">
              <div className="flex h-[70vh] w-screen flex-col justify-between">
                <div className="text-center">
                  <h1 className="text-4xl font-bold sm:text-5xl">Model 3</h1>
                  <Link
                    className="font-mono underline underline-offset-2"
                    href={"/test-drive"}
                  >
                    Schedule a Test Drive
                  </Link>
                </div>
                <div className="flex w-full py-4 md:justify-center">
                  <div className="grid w-full grid-cols-1 gap-4 px-6 md:w-auto md:grid-cols-2 lg:w-[40%]">
                    <CtaButton displayText="Buy Now" primary />
                    <CtaButton displayText="Custom Order" primary={false} />
                  </div>
                </div>
              </div>
            </div>
            <div className="absolute bottom-4 left-1/2 right-1/2">
              <SlideButton />
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
